# Generated by Django 3.0.7 on 2020-11-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='specie',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='strain',
        ),
    ]
